/*
*	Copyright (C) 2011 Life Technologies Inc.
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CoordSelectionPanel.java
 *
 * Created on 23.06.2011, 08:50:01
 */
package com.iontorrent.guiutils.wells;

import com.iontorrent.wellmodel.WellCoordinate;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Chantal Roth
 */
public class CoordSelectionPanel extends javax.swing.JPanel {

    /** Creates new form CoordSelectionPanel */
    public CoordSelectionPanel() {
        initComponents();
    }
    public WellCoordinate getCoord1() {
        int x1 = ((Integer)this.spinX1.getValue()).intValue();
        int y1 = ((Integer)this.spinY1.getValue()).intValue();
        return new WellCoordinate(x1, y1);
    }
    
    public WellCoordinate getCoord2() {
        int x1 = ((Integer)this.spinX1.getValue()).intValue();
        int y1 = ((Integer)this.spinY1.getValue()).intValue();
        
        int x2 = x1+((Integer)this.spinX2.getValue()).intValue();
        int y2 = y1+((Integer)this.spinY2.getValue()).intValue();
        return new WellCoordinate(x2, y2);
    }
    public void setCoord1(WellCoordinate coord1) {
        this.spinX1.setValue(coord1.getX());
        this.spinY1.setValue(coord1.getY());
    }
    public void setCoord2(WellCoordinate coord1) {
        this.spinX2.setValue(coord1.getX());
        this.spinY2.setValue(coord1.getY());
    }
    public void setMaxX(int x) {
        ((SpinnerNumberModel)this.spinX1.getModel()).setMaximum(x);
       // ((SpinnerNumberModel)this.spinX2.getModel()).setMaximum(x);
    }
     public void setMaxY(int y) {
        ((SpinnerNumberModel)this.spinY1.getModel()).setMaximum(y);
       // ((SpinnerNumberModel)this.spinY2.getModel()).setMaximum(y);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spinX1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spinY1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spinX2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spinY2 = new javax.swing.JSpinner();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(CoordSelectionPanel.class, "CoordSelectionPanel.jLabel1.text")); // NOI18N

        spinX1.setModel(new javax.swing.SpinnerNumberModel(500, 0, 4096, 100));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(CoordSelectionPanel.class, "CoordSelectionPanel.jLabel2.text")); // NOI18N

        spinY1.setModel(new javax.swing.SpinnerNumberModel(500, 0, 4096, 100));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(CoordSelectionPanel.class, "CoordSelectionPanel.jLabel3.text")); // NOI18N

        spinX2.setModel(new javax.swing.SpinnerNumberModel(50, 0, 200, 10));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(CoordSelectionPanel.class, "CoordSelectionPanel.jLabel4.text")); // NOI18N

        spinY2.setModel(new javax.swing.SpinnerNumberModel(50, 0, 200, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinX1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinY1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinX2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinY2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(spinY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spinX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(spinY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spinX1;
    private javax.swing.JSpinner spinX2;
    private javax.swing.JSpinner spinY1;
    private javax.swing.JSpinner spinY2;
    // End of variables declaration//GEN-END:variables
}
