/*
*	Copyright (C) 2011 Life Technologies Inc.
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WellFilterPanel.java
 *
 * Created on 06.04.2011, 09:33:02
 */
package com.iontorrent.welltable;

import com.iontorrent.guiutils.MinMaxPanel;
import com.iontorrent.rawdataaccess.wells.ScoreMaskFlag;
import com.iontorrent.wellmodel.WellContext;
import com.iontorrent.wellmodel.WellFilter;
import com.iontorrent.wellmodel.WellScoreMaskFilter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Chantal Roth
 */
public class ScoreMaskFilterPanel extends javax.swing.JPanel {

    WellContext context;

    /** Creates new form WellFilterPanel */
    public ScoreMaskFilterPanel(WellContext context) {
        initComponents();
        this.context = context;
        ScoreMaskFlag flags[] = ScoreMaskFlag.values();

        jList1.setModel(new javax.swing.DefaultComboBoxModel(flags));

    }

    public void setSelected(ArrayList<WellFilter> filters) {
        if (filters == null) {
            return;
        }
        for (WellFilter f : filters) {
            if (f instanceof WellScoreMaskFilter) {
                ScoreMaskFlag flag = ((WellScoreMaskFilter) f).getFlag();
                jList1.setSelectedValue(flag, false);
            }
        }
    }

    public void setSelectedFlags(ArrayList<ScoreMaskFlag> flags) {
        if (flags == null) {
            return;
        }
        for (ScoreMaskFlag f : flags) {
            jList1.setSelectedValue(f, false);

        }
    }

    public ArrayList<WellFilter> getSelectedFilters() {
        ArrayList<WellFilter> filters = new ArrayList<WellFilter>();
        Object[] selected = jList1.getSelectedValues();
        for (int i = 0; i < selected.length; i++) {
            ScoreMaskFlag flag = (ScoreMaskFlag) selected[i];
            double min = 1;
            double max = 10000;
            MinMaxPanel p = new MinMaxPanel();
            int ans = JOptionPane.showConfirmDialog(this, p, "Interval for " + flag.getName(), JOptionPane.OK_OPTION);
            if (ans != JOptionPane.CANCEL_OPTION) {
                min = p.getMin();
                max = p.getMax();

                WellScoreMaskFilter fil = new WellScoreMaskFilter(flag, min, max);
                filters.add(fil);

            }
        }
        return filters;
    }

    public ArrayList<ScoreMaskFlag> getSelectedFlags() {
        ArrayList<ScoreMaskFlag> flags = new ArrayList<ScoreMaskFlag>();
        Object[] selected = jList1.getSelectedValues();
        for (int i = 0; i < selected.length; i++) {
            ScoreMaskFlag flag = (ScoreMaskFlag) selected[i];
            flags.add(flag);
        }
        return flags;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Select score filters:"));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(WellFilterPanel.class, "WellFilterPanel.jLabel1.text")); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {

            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {
                return strings.length;
            }

            public Object getElementAt(int i) {
                return strings[i];
            }
        });
        jList1.setToolTipText(org.openide.util.NbBundle.getMessage(WellFilterPanel.class, "WellFilterPanel.jList1.toolTipText")); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jButton1.setText(org.openide.util.NbBundle.getMessage(WellFilterPanel.class, "WellFilterPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE).addGroup(layout.createSequentialGroup().addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE).addContainerGap()).addGroup(layout.createSequentialGroup().addComponent(jButton1).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton1)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jList1.setSelectedIndices(null);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
