/*
*	Copyright (C) 2011 Life Technologies Inc.
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomePanel.java
 *
 * Created on 31.03.2011, 12:28:10
 */

package com.iontorrent.main.startup;

import com.iontorrent.utils.io.FileTools;
import java.io.File;

/**
 *
 * @author Chantal Roth
 */
public class WelcomePanel extends javax.swing.JPanel {

    
    String cache_dir;
    
    /** Creates new form WelcomePanel */
    public WelcomePanel() {
        initComponents();
    }

    WelcomePanel(String cache_dir, String server) {
        this.cache_dir = cache_dir;
        initComponents();
     
    }
    
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        jEditorPane1.setContentType(org.openide.util.NbBundle.getMessage(WelcomePanel.class, "WelcomePanel.jEditorPane1.contentType")); // NOI18N
        jEditorPane1.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n  \n      \r<h1>Welcome to TorrentScout!</h1>\n<p>\nThe first time you use this tool, there are a few things to check: in the following settings panel, make sure that the rules to access the <b>raw, results and cache directories</b> make sense, and that you select a <b>torrent server</b> that has a database (it is not required, but would be nice :-).</p>\n<p>\nAnd here a hint of how to get started:\n<ul>\n<li>Select the <b>ExperimentViewer</b> component and select an experiment and <b>result</b>\n(this will set the context to the directories etc)\n<li>Next, select the MaskView component. If the file path looks ok, click refresh to load the data.\n<li>Pick a small area of the chip, and then you should see a table with the selected wells\n<li>Pick a row in the table to view further details\n<li><font color='aa0000'><b>Now the tool will probalby index an .sff file which may take a minute <b></font>\n<li>If you also want to view raw data, the tool will have to <b>convert the raw data files</b> to a format that allows <b>fast access</b>. \nYou will see a table where you can select <b>how many flows you wish to convert</b>.\n<font color='aa0000'>The conversion might take a few minutes</font><br>\n After this conversion is done, you will be able to view the raw data. This happens for every new experiment you look at.\n</ul>\n</p>\n\nAnd here a few more tips:\n<ul>\n<li>You can select the window position by <b>right clicking on the title bar of the window and selecting the location</b>\n<li>You can also move windows around  by <b>dragging the window</b>\n<li>If you can't see a component or have closed it, go to Menu <b>window</b> and select it again.\n</ul>\n  \n  </body>\r\n</html>\r\n"); // NOI18N
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
