/*
 * Copyright (C) 2011 Life Technologies Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * WidgetPanel.java
 *
 * Created on 03.11.2011, 12:32:17
 */
package com.iontorrent.torrentscout.explorer;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Chantal Roth
 */
public class WidgetPanel extends javax.swing.JPanel {

    ExplorerContext maincont;

    /** Creates new form WidgetPanel */
    public WidgetPanel(ExplorerContext maincont) {
        initComponents();
        this.maincont = maincont;

        ArrayList<Widget> list = maincont.getWidgets();
        setLayout(new GridLayout(list.size(), 2));
        for (Widget w : list) {
            //add(new JLabel(w.getName()+":"+w.getColor()));
//            JLabel lbl = new JLabel("   ");

            add(new WidgetLabel(w));
            //lbl.setBackground(w.getColor());
            // lbl.setToolTipText(w.toString());
            //   lbl.set
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
