/*
*	Copyright (C) 2011 Life Technologies Inc.
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExpFilterPanel.java
 *
 * Created on 13.04.2011, 09:46:03
 */

package com.iontorrent.scout.experimentviewer.exptree;

import java.util.ArrayList;

/**
 *
 * @author Chantal Roth
 */
public class ExpFilterPanel extends javax.swing.JPanel {

    static NodeFilter[] FILTERS = { 
        new ExpDateNodeFilter(3), 
        new ExpDateNodeFilter(7), 
        new ExpDateNodeFilter(14), 
        new ExpDateNodeFilter(30), 
        new ExpDateNodeFilter(60), 
        new ExpDateNodeFilter(90),
         new RunNamesNodeFilter("", false),
    new ExpNamesNodeFilter("", false),
    new ExpChiptypeNodeFilter("314"),
    new ExpChiptypeNodeFilter("314", true),
    new ExpChiptypeNodeFilter("316"), 
    new ExpChiptypeNodeFilter("318"),
    new ExpChiptypeNodeFilter("900"),
    new RunStatusNodeFilter("complete"), 
    new ExpStatusNodeFilter("complete"),
    new RunStatusNodeFilter("complete", true), 
    new ExpStatusNodeFilter("complete", true),
   
            
    };
    
    /** Creates new form ExpFilterPanel */
    public ExpFilterPanel() {
        initComponents();
        
        jList1.setModel(new javax.swing.DefaultComboBoxModel(FILTERS));
    }

    public static NodeFilter getDefaultFilter() {
        return FILTERS[1];
    }
     public void setSelected(ArrayList<NodeFilter> filters) {
        if (filters == null) return;
        for (NodeFilter f: filters) {
                jList1.setSelectedValue(f, false);
        }
    }
    public ArrayList<NodeFilter> getSelectedFilters() {
        ArrayList<NodeFilter>  filters = new ArrayList<NodeFilter> ();
        Object[] selected = jList1.getSelectedValues();
        for (int i = 0; i < selected.length; i++)        {
            NodeFilter f = (NodeFilter)selected[i];            
            filters.add(f);
        }
        return filters;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ExpFilterPanel.class, "ExpFilterPanel.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ExpFilterPanel.class, "ExpFilterPanel.jLabel1.text")); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText(org.openide.util.NbBundle.getMessage(ExpFilterPanel.class, "ExpFilterPanel.jList1.toolTipText")); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jButton1.setText(org.openide.util.NbBundle.getMessage(ExpFilterPanel.class, "ExpFilterPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jList1.clearSelection();
        
}//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
