/*
*	Copyright (C) 2011 Life Technologies Inc.
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 2 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.ionogram.options;

import com.iontorrent.guiutils.GuiUtils;
import java.awt.Color;
import java.util.prefs.Preferences;
import javax.swing.JButton;
import javax.swing.JColorChooser;

public final class IonogramOptionsPanel extends javax.swing.JPanel {

    private final IonogramOptionsOptionsPanelController controller;

    IonogramOptionsPanel(IonogramOptionsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnG = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnC = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(IonogramOptionsPanel.class, "IonogramOptionsPanel.jPanel1.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(IonogramOptionsPanel.class, "IonogramOptionsPanel.jLabel1.text")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard bar chart", "Simple GATC chart (no bars :-)" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(IonogramOptionsPanel.class, "IonogramOptionsPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnG, org.openide.util.NbBundle.getMessage(IonogramOptionsPanel.class, "IonogramOptionsPanel.btnG.text")); // NOI18N
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnA, org.openide.util.NbBundle.getMessage(IonogramOptionsPanel.class, "IonogramOptionsPanel.btnA.text")); // NOI18N
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnT, org.openide.util.NbBundle.getMessage(IonogramOptionsPanel.class, "IonogramOptionsPanel.btnT.text")); // NOI18N
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnC, org.openide.util.NbBundle.getMessage(IonogramOptionsPanel.class, "IonogramOptionsPanel.btnC.text")); // NOI18N
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnC))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnG)
                    .addComponent(btnA)
                    .addComponent(btnT)
                    .addComponent(btnC))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        Color c = JColorChooser.showDialog(this, "Color for A", btnA.getBackground());
        btnA.setBackground(c);
        checkColors(btnA);
      
    }//GEN-LAST:event_btnAActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        Color c = JColorChooser.showDialog(this, "Color for G", btnG.getBackground());
        btnG.setBackground(c);
        checkColors(btnG);
       
    }//GEN-LAST:event_btnGActionPerformed

    private void checkColors(JButton btn) {
        Color c = btn.getBackground();
        int n = c.getRed() + c.getBlue()+ c.getGreen();
        if (n/3<75) {
            btn.setForeground(Color.white);
        }
        else btn.setForeground(Color.black);
    }
    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        Color c = JColorChooser.showDialog(this, "Color for T", btnT.getBackground());        
        btnT.setBackground(c);
        checkColors(btnT);
       
    }//GEN-LAST:event_btnTActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        Color c = JColorChooser.showDialog(this, "Color for C", btnC.getBackground());
        btnC.setBackground(c);
        checkColors(btnC);
       
    }//GEN-LAST:event_btnCActionPerformed

    void load() {
        // TODO read settings and initialize GUI
        // Example:        
        // someCheckBox.setSelected(Preferences.userNodeForPackage(IonogramOptionsPanel.class).getBoolean("someFlag", false));
        // or for org.openide.util with API spec. version >= 7.4:
        // someCheckBox.setSelected(NbPreferences.forModule(IonogramOptionsPanel.class).getBoolean("someFlag", false));
        // or:
        // someTextField.setText(SomeSystemOption.getDefault().getSomeStringProperty());
        Preferences p =  Preferences.userNodeForPackage(IonogramOptionsPanel.class);
        String chart_type = p.get("chart_type", "standard bar chart");
        this.jComboBox1.setSelectedItem(chart_type);
        String colT = p.get("color_T", "AA0000");
        String colA = p.get("color_A", "00AA00");
        String colC = p.get("color_C", "0000AA");
        String colG = p.get("color_G", "000000");
        btnG.setBackground(GuiUtils.stringToColor(colG));
        btnA.setBackground(GuiUtils.stringToColor(colA));
        btnT.setBackground(GuiUtils.stringToColor(colT));
        btnC.setBackground(GuiUtils.stringToColor(colC));
        checkColors(btnG);
        checkColors(btnA);
        checkColors(btnT);
        checkColors(btnC);
    }

   

    void store() {
        // TODO store modified settings
        // Example:
        // Preferences.userNodeForPackage(IonogramOptionsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or for org.openide.util with API spec. version >= 7.4:
        // NbPreferences.forModule(IonogramOptionsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        // or:
        // SomeSystemOption.getDefault().setSomeStringProperty(someTextField.getText());
        String hexG = Integer.toHexString(btnG.getBackground().getRGB());
        String hexA = Integer.toHexString(btnA.getBackground().getRGB());
        String hexT = Integer.toHexString(btnT.getBackground().getRGB());
        String hexC = Integer.toHexString(btnC.getBackground().getRGB());
        p("Color Ghex string:"+hexG);
        p("Color Ahex string:"+hexA);
        p("Color Thex string:"+hexT);
        p("Color Chex string:"+hexC);
        
        Preferences p = Preferences.userNodeForPackage(IonogramOptionsPanel.class);
        p.put("color_G", hexG);
        p.put("color_A", hexA);
        p.put("color_T", hexT);
        p.put("color_C", hexC);
        String chart_type = ""+this.jComboBox1.getSelectedItem();
        p.put("chart_type", chart_type);
        p("Ionograms preferences path: "+p.absolutePath());
                
//        try {
//            p.sync();
//        } catch (BackingStoreException ex) {
//            Exceptions.printStackTrace(ex);
//        }
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnT;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void p(String string) {
        System.out.println("IonogramOptionsPanel: "+string);
    }
}
